AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/**/*'
    - 'activegraphql.gemspec'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/Count:
  Enabled: false

Metrics/ClassLength:
  Max: 150
